#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake
# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
#application=$(getApplication)

#runApplication "$application"
#runApplication foamMeshToFluent
#runApplication foamDataToFluent

#------------------------------------------------------------------------------
